sudo: required
services:
    - docker

before_install:
    - docker build -t rafaelnasc1mento/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run rafaelnasc1mento/react-test npm test -- --coverage
    
after_sucess:
    - docker build -t rafaelnasc1mento/multi-client ./client
    - docker build -t rafaelnasc1mento/multi-nginx ./nginx
    - docker build -t rafaelnasc1mento/multi-server ./server    
    - docker build -t rafaelnasc1mento/multi-worker ./worker
    # log in to the docker CLI
    # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Take those images and push them to docker hub
    # - docker push rafaelnasc1mento/multi-client
    # - docker push rafaelnasc1mento/multi-nginx
    # - docker push rafaelnasc1mento/multi-server
    # - docker push rafaelnasc1mento/multi-worker
